import { TRENDING_AIRCRAFT } from '../types';
// import { v4 as uuidV4 } from 'uuid';

import jet1 from '../../assets/gulf-19-1.jpg';
import jet2 from '../../assets//129776_Screen_Shot_2023-11-08_at_1.41.35_PM.png';
import jet3 from '../../assets/2004-Embraer.jpg';
import jet4 from '../../assets/learjet4.jpg';
import jet5 from '../../assets/global-2014-1.jpg';
import jet6 from '../../assets/airbus1.jpg';
import jet7 from '../../assets/129199_13_GulfstreamG650_sn6037-Ext1.jpg';
import jet8 from '../../assets/130285_99_KingAirB200_snBB-1663-Ext1.jpg';
import gulf6501 from '../../assets/129776_19_GulfstreamG650ER_snNA-Int11.jpg';
import gulf6502 from '../../assets/129776_19_GulfstreamG650ER_snNA-Int12.jpg';
import gulf6503 from '../../assets/129776_19_GulfstreamG650ER_snNA-Int2.jpg';
import gulf6504 from '../../assets/129776_19_GulfstreamG650ER_snNA-Int4.jpg';
import gulf6508 from '../../assets/129776_Screen_Shot_2023-11-08_at_1.41.35_PM (1).png';

// import gulf6505 from '../../assets/129776_19_GulfstreamG650ER_snNA-Int6.jpg';
// import gulf6506 from '../../assets/129776_19_GulfstreamG650ER_snNA-Int7.jpg';
// import gulf6507 from '../../assets/129776_19_GulfstreamG650ER_snNA-Int9.jpg';

// import gulf6509 from '../../assets/129776_Screen_Shot_2023-11-08_at_1.41.35_PM (1).png';
// import gulf6510 from '../../assets/GulfstreamG650ER_snNA-Int1.jpg';

const initialState = {
  trendingAircrafts: [
    {
      jetName: '1985 Gulfstream III',
      jetType: 'Jet Aircraft',
      jetPix: jet1,
      jetViews: 95,
      jetId: '24410089-73f7-4d02-87ee-4f5198fe73b81',
      jetPics: [
        gulf6501,
        gulf6502,
        gulf6503,
        gulf6504,
        // gulf6505,
        // gulf6506,
        // gulf6507,
        // gulf6508,
        // gulf6510,
      ],
      jetPrice: '$49,950,000',
      jetMainPic: gulf6508,
      summary: [
        'Exclusive Listing',
        'Low Flight hours',
        'One owner since new',
        'Private use only',
        'Forward Galley',
        'Four zone, 17 passenger configuration',
        'RRCC and MSP',
        '2020 mandates complied with',
        'WIFI',
        'Maintenance complied with at Gulfstream authorized facilities',
        'Four single VIP club seats',
        'Three place divan opposite two single VIP club seats',
        'Four place conference table',
        'Two 3 place divans (Two each TTOL seats)',
        'Additional valuable equipment / materials included in sale',
      ],
      serialNumber: 'https://www.globalair.com/ac-reg/search.aspx?serial=6354',
      regNum: 'https://www.globalair.com/ac-reg/search.aspx?regnum=B-603R',
      manufacturer: 'Gulfstream Aerospace',
      year: '2019',
      location: 'China',
      time: '582 hrs',
      address: `88 East Main St  Mendham New Jersey (USA) 07945`,
      name: 'Philip Rushton',
      avionics: [
        '4 Honeywell DU-1310 EFIS',
        '3 Honeywell CDU',
        '3 Honeywell LASEREF VI IRS',
        '2 Honeywell GPS',
        '2 Honeywell DM-855 DME',
        '1 Gulfstream HGS-6250 HUD',
        '1 KollsmaEVS',
        '2 Honeywell DF-855 ADF',
        '2 Honeywell AH-1000 AHRS',
        '1 Honeywell NC-860A VHF COM',
        '2 Honeywell TR-865A VHF COM',
        '2 Collins HF-9034A w/SECAL HF COM',
        '1 Honeywell MCS-7120 SATCOM',
        '1 Honeywell TR-1 WRADAR',
        '2 Honeywell Mode S XPNDR',
        '1 Honeywell TCAS II w/change7.1 TCAS',
        '2 Honeywell EGP-100 GPWS',
        '1 Universal CVR-120R CVR',
        '1 Universal FDR-25 FDR',
        '1 Honeywell LP-860 LSS',
      ],
      status: '48 month completed in March 2023',
      features:
        'Owner prepared to close in 2023 and escrow agreed funds for an ARCS in early 2024.',
    },
    {
      jetName: '2019 Gulfstream G650ER',
      jetType: 'Jet Aircraft',
      jetPix: jet2,
      jetViews: 87,
      jetId: '24410089-73f7-4d02-87ee-4f5198fe73b82',

      jetPics: [
        gulf6501,
        gulf6502,
        gulf6503,
        gulf6504,
        // gulf6505,
        // gulf6506,
        // gulf6507,
        // gulf6508,
        // gulf6510,
      ],
      jetPrice: '$49,950,000',
      jetMainPic: gulf6508,
      summary: [
        'Exclusive Listing',
        'Low Flight hours',
        'One owner since new',
        'Private use only',
        'Forward Galley',
        'Four zone, 17 passenger configuration',
        'RRCC and MSP',
        '2020 mandates complied with',
        'WIFI',
        'Maintenance complied with at Gulfstream authorized facilities',
        'Four single VIP club seats',
        'Three place divan opposite two single VIP club seats',
        'Four place conference table',
        'Two 3 place divans (Two each TTOL seats)',
        'Additional valuable equipment / materials included in sale',
      ],
      serialNumber: 'https://www.globalair.com/ac-reg/search.aspx?serial=6354',
      regNum: 'https://www.globalair.com/ac-reg/search.aspx?regnum=B-603R',
      manufacturer: 'Gulfstream Aerospace',
      year: '2019',
      location: 'China',
      time: '582 hrs',
      address: `88 East Main St ${(<br />)} Mendham New Jersey (USA) 07945`,
      name: 'Philip Rushton',
      avionics: [
        '4 Honeywell DU-1310 EFIS',
        '3 Honeywell CDU',
        '3 Honeywell LASEREF VI IRS',
        '2 Honeywell GPS',
        '2 Honeywell DM-855 DME',
        '1 Gulfstream HGS-6250 HUD',
        '1 KollsmaEVS',
        '2 Honeywell DF-855 ADF',
        '2 Honeywell AH-1000 AHRS',
        '1 Honeywell NC-860A VHF COM',
        '2 Honeywell TR-865A VHF COM',
        '2 Collins HF-9034A w/SECAL HF COM',
        '1 Honeywell MCS-7120 SATCOM',
        '1 Honeywell TR-1 WRADAR',
        '2 Honeywell Mode S XPNDR',
        '1 Honeywell TCAS II w/change7.1 TCAS',
        '2 Honeywell EGP-100 GPWS',
        '1 Universal CVR-120R CVR',
        '1 Universal FDR-25 FDR',
        '1 Honeywell LP-860 LSS',
      ],
      status: '48 month completed in March 2023',
      features:
        'Owner prepared to close in 2023 and escrow agreed funds for an ARCS in early 2024.',
    },
    {
      jetName: ' 2004 Embraer ERJ-145LR',
      jetType: 'Jet Aircraft',
      jetPix: jet3,
      jetViews: 130,
      jetId: '24410089-73f7-4d02-87ee-4f5198fe73b83',

      jetPics: [
        gulf6501,
        gulf6502,
        gulf6503,
        gulf6504,
        // gulf6505,
        // gulf6506,
        // gulf6507,
        // gulf6508,
        // gulf6510,
      ],
      jetPrice: '$49,950,000',
      jetMainPic: gulf6508,
      summary: [
        'Exclusive Listing',
        'Low Flight hours',
        'One owner since new',
        'Private use only',
        'Forward Galley',
        'Four zone, 17 passenger configuration',
        'RRCC and MSP',
        '2020 mandates complied with',
        'WIFI',
        'Maintenance complied with at Gulfstream authorized facilities',
        'Four single VIP club seats',
        'Three place divan opposite two single VIP club seats',
        'Four place conference table',
        'Two 3 place divans (Two each TTOL seats)',
        'Additional valuable equipment / materials included in sale',
      ],
      serialNumber: 'https://www.globalair.com/ac-reg/search.aspx?serial=6354',
      regNum: 'https://www.globalair.com/ac-reg/search.aspx?regnum=B-603R',
      manufacturer: 'Gulfstream Aerospace',
      year: '2019',
      location: 'China',
      time: '582 hrs',
      address: `88 East Main St ${(<br />)} Mendham New Jersey (USA) 07945`,
      name: 'Philip Rushton',
      avionics: [
        '4 Honeywell DU-1310 EFIS',
        '3 Honeywell CDU',
        '3 Honeywell LASEREF VI IRS',
        '2 Honeywell GPS',
        '2 Honeywell DM-855 DME',
        '1 Gulfstream HGS-6250 HUD',
        '1 KollsmaEVS',
        '2 Honeywell DF-855 ADF',
        '2 Honeywell AH-1000 AHRS',
        '1 Honeywell NC-860A VHF COM',
        '2 Honeywell TR-865A VHF COM',
        '2 Collins HF-9034A w/SECAL HF COM',
        '1 Honeywell MCS-7120 SATCOM',
        '1 Honeywell TR-1 WRADAR',
        '2 Honeywell Mode S XPNDR',
        '1 Honeywell TCAS II w/change7.1 TCAS',
        '2 Honeywell EGP-100 GPWS',
        '1 Universal CVR-120R CVR',
        '1 Universal FDR-25 FDR',
        '1 Honeywell LP-860 LSS',
      ],
      status: '48 month completed in March 2023',
      features:
        'Owner prepared to close in 2023 and escrow agreed funds for an ARCS in early 2024.',
    },
    {
      jetName: ' 2002 Learjet 45',
      jetType: 'Jet Aircraft',
      jetPix: jet4,
      jetViews: 163,
      jetId: '24410089-73f7-4d02-87ee-4f5198fe73b84',

      jetPics: [
        gulf6501,
        gulf6502,
        gulf6503,
        gulf6504,
        // gulf6505,
        // gulf6506,
        // gulf6507,
        // gulf6508,
        // gulf6510,
      ],
      jetPrice: '$49,950,000',
      jetMainPic: gulf6508,
      summary: [
        'Exclusive Listing',
        'Low Flight hours',
        'One owner since new',
        'Private use only',
        'Forward Galley',
        'Four zone, 17 passenger configuration',
        'RRCC and MSP',
        '2020 mandates complied with',
        'WIFI',
        'Maintenance complied with at Gulfstream authorized facilities',
        'Four single VIP club seats',
        'Three place divan opposite two single VIP club seats',
        'Four place conference table',
        'Two 3 place divans (Two each TTOL seats)',
        'Additional valuable equipment / materials included in sale',
      ],
      serialNumber: 'https://www.globalair.com/ac-reg/search.aspx?serial=6354',
      regNum: 'https://www.globalair.com/ac-reg/search.aspx?regnum=B-603R',
      manufacturer: 'Gulfstream Aerospace',
      year: '2019',
      location: 'China',
      time: '582 hrs',
      address: `88 East Main St ${(<br />)} Mendham New Jersey (USA) 07945`,
      name: 'Philip Rushton',
      avionics: [
        '4 Honeywell DU-1310 EFIS',
        '3 Honeywell CDU',
        '3 Honeywell LASEREF VI IRS',
        '2 Honeywell GPS',
        '2 Honeywell DM-855 DME',
        '1 Gulfstream HGS-6250 HUD',
        '1 KollsmaEVS',
        '2 Honeywell DF-855 ADF',
        '2 Honeywell AH-1000 AHRS',
        '1 Honeywell NC-860A VHF COM',
        '2 Honeywell TR-865A VHF COM',
        '2 Collins HF-9034A w/SECAL HF COM',
        '1 Honeywell MCS-7120 SATCOM',
        '1 Honeywell TR-1 WRADAR',
        '2 Honeywell Mode S XPNDR',
        '1 Honeywell TCAS II w/change7.1 TCAS',
        '2 Honeywell EGP-100 GPWS',
        '1 Universal CVR-120R CVR',
        '1 Universal FDR-25 FDR',
        '1 Honeywell LP-860 LSS',
      ],
      status: '48 month completed in March 2023',
      features:
        'Owner prepared to close in 2023 and escrow agreed funds for an ARCS in early 2024.',
    },
    {
      jetName: '2014 Global 5000',
      jetType: 'Commercial Aircraft',
      jetPix: jet5,
      jetViews: 95,
      jetId: '24410089-73f7-4d02-87ee-4f5198fe73b85',

      jetPics: [
        gulf6501,
        gulf6502,
        gulf6503,
        gulf6504,
        // gulf6505,
        // gulf6506,
        // gulf6507,
        // gulf6508,
        // gulf6510,
      ],
      jetPrice: '$49,950,000',
      jetMainPic: gulf6508,
      summary: [
        'Exclusive Listing',
        'Low Flight hours',
        'One owner since new',
        'Private use only',
        'Forward Galley',
        'Four zone, 17 passenger configuration',
        'RRCC and MSP',
        '2020 mandates complied with',
        'WIFI',
        'Maintenance complied with at Gulfstream authorized facilities',
        'Four single VIP club seats',
        'Three place divan opposite two single VIP club seats',
        'Four place conference table',
        'Two 3 place divans (Two each TTOL seats)',
        'Additional valuable equipment / materials included in sale',
      ],
      serialNumber: 'https://www.globalair.com/ac-reg/search.aspx?serial=6354',
      regNum: 'https://www.globalair.com/ac-reg/search.aspx?regnum=B-603R',
      manufacturer: 'Gulfstream Aerospace',
      year: '2019',
      location: 'China',
      time: '582 hrs',
      address: `88 East Main St ${(<br />)} Mendham New Jersey (USA) 07945`,
      name: 'Philip Rushton',
      avionics: [
        '4 Honeywell DU-1310 EFIS',
        '3 Honeywell CDU',
        '3 Honeywell LASEREF VI IRS',
        '2 Honeywell GPS',
        '2 Honeywell DM-855 DME',
        '1 Gulfstream HGS-6250 HUD',
        '1 KollsmaEVS',
        '2 Honeywell DF-855 ADF',
        '2 Honeywell AH-1000 AHRS',
        '1 Honeywell NC-860A VHF COM',
        '2 Honeywell TR-865A VHF COM',
        '2 Collins HF-9034A w/SECAL HF COM',
        '1 Honeywell MCS-7120 SATCOM',
        '1 Honeywell TR-1 WRADAR',
        '2 Honeywell Mode S XPNDR',
        '1 Honeywell TCAS II w/change7.1 TCAS',
        '2 Honeywell EGP-100 GPWS',
        '1 Universal CVR-120R CVR',
        '1 Universal FDR-25 FDR',
        '1 Honeywell LP-860 LSS',
      ],
      status: '48 month completed in March 2023',
      features:
        'Owner prepared to close in 2023 and escrow agreed funds for an ARCS in early 2024.',
    },
    {
      jetName: '2021 Airbus ACJ319neo',
      jetType: 'Jet Aircraft',
      jetPix: jet6,
      jetViews: 175,
      jetId: '24410089-73f7-4d02-87ee-4f5198fe73b86',

      jetPics: [
        gulf6501,
        gulf6502,
        gulf6503,
        gulf6504,
        // gulf6505,
        // gulf6506,
        // gulf6507,
        // gulf6508,
        // gulf6510,
      ],
      jetPrice: '$49,950,000',
      jetMainPic: gulf6508,
      summary: [
        'Exclusive Listing',
        'Low Flight hours',
        'One owner since new',
        'Private use only',
        'Forward Galley',
        'Four zone, 17 passenger configuration',
        'RRCC and MSP',
        '2020 mandates complied with',
        'WIFI',
        'Maintenance complied with at Gulfstream authorized facilities',
        'Four single VIP club seats',
        'Three place divan opposite two single VIP club seats',
        'Four place conference table',
        'Two 3 place divans (Two each TTOL seats)',
        'Additional valuable equipment / materials included in sale',
      ],
      serialNumber: 'https://www.globalair.com/ac-reg/search.aspx?serial=6354',
      regNum: 'https://www.globalair.com/ac-reg/search.aspx?regnum=B-603R',
      manufacturer: 'Gulfstream Aerospace',
      year: '2019',
      location: 'China',
      time: '582 hrs',
      address: `88 East Main St ${(<br />)} Mendham New Jersey (USA) 07945`,
      name: 'Philip Rushton',
      avionics: [
        '4 Honeywell DU-1310 EFIS',
        '3 Honeywell CDU',
        '3 Honeywell LASEREF VI IRS',
        '2 Honeywell GPS',
        '2 Honeywell DM-855 DME',
        '1 Gulfstream HGS-6250 HUD',
        '1 KollsmaEVS',
        '2 Honeywell DF-855 ADF',
        '2 Honeywell AH-1000 AHRS',
        '1 Honeywell NC-860A VHF COM',
        '2 Honeywell TR-865A VHF COM',
        '2 Collins HF-9034A w/SECAL HF COM',
        '1 Honeywell MCS-7120 SATCOM',
        '1 Honeywell TR-1 WRADAR',
        '2 Honeywell Mode S XPNDR',
        '1 Honeywell TCAS II w/change7.1 TCAS',
        '2 Honeywell EGP-100 GPWS',
        '1 Universal CVR-120R CVR',
        '1 Universal FDR-25 FDR',
        '1 Honeywell LP-860 LSS',
      ],
      status: '48 month completed in March 2023',
      features:
        'Owner prepared to close in 2023 and escrow agreed funds for an ARCS in early 2024.',
    },
    {
      jetName: '2013 Gulfstream G650',
      jetType: 'Twin Turbo-Prop Aircraft',
      jetPix: jet7,
      jetViews: 200,
      jetId: '24410089-73f7-4d02-87ee-4f5198fe73b87',

      jetPics: [
        gulf6501,
        gulf6502,
        gulf6503,
        gulf6504,
        // gulf6505,
        // gulf6506,
        // gulf6507,
        // gulf6508,
        // gulf6510,
      ],
      jetPrice: '$49,950,000',
      jetMainPic: gulf6508,
      summary: [
        'Exclusive Listing',
        'Low Flight hours',
        'One owner since new',
        'Private use only',
        'Forward Galley',
        'Four zone, 17 passenger configuration',
        'RRCC and MSP',
        '2020 mandates complied with',
        'WIFI',
        'Maintenance complied with at Gulfstream authorized facilities',
        'Four single VIP club seats',
        'Three place divan opposite two single VIP club seats',
        'Four place conference table',
        'Two 3 place divans (Two each TTOL seats)',
        'Additional valuable equipment / materials included in sale',
      ],
      serialNumber: 'https://www.globalair.com/ac-reg/search.aspx?serial=6354',
      regNum: 'https://www.globalair.com/ac-reg/search.aspx?regnum=B-603R',
      manufacturer: 'Gulfstream Aerospace',
      year: '2019',
      location: 'China',
      time: '582 hrs',
      address: `88 East Main St ${(<br />)} Mendham New Jersey (USA) 07945`,
      name: 'Philip Rushton',
      avionics: [
        '4 Honeywell DU-1310 EFIS',
        '3 Honeywell CDU',
        '3 Honeywell LASEREF VI IRS',
        '2 Honeywell GPS',
        '2 Honeywell DM-855 DME',
        '1 Gulfstream HGS-6250 HUD',
        '1 KollsmaEVS',
        '2 Honeywell DF-855 ADF',
        '2 Honeywell AH-1000 AHRS',
        '1 Honeywell NC-860A VHF COM',
        '2 Honeywell TR-865A VHF COM',
        '2 Collins HF-9034A w/SECAL HF COM',
        '1 Honeywell MCS-7120 SATCOM',
        '1 Honeywell TR-1 WRADAR',
        '2 Honeywell Mode S XPNDR',
        '1 Honeywell TCAS II w/change7.1 TCAS',
        '2 Honeywell EGP-100 GPWS',
        '1 Universal CVR-120R CVR',
        '1 Universal FDR-25 FDR',
        '1 Honeywell LP-860 LSS',
      ],
      status: '48 month completed in March 2023',
      features:
        'Owner prepared to close in 2023 and escrow agreed funds for an ARCS in early 2024.',
    },
    {
      jetName: '1999 King Air B200',
      jetType: 'Jet Aircraft',
      jetPix: jet8,
      jetViews: 145,
      jetId: '24410089-73f7-4d02-87ee-4f5198fe73b88',

      jetPics: [
        gulf6501,
        gulf6502,
        gulf6503,
        gulf6504,
        // gulf6505,
        // gulf6506,
        // gulf6507,
        // gulf6508,
        // gulf6510,
      ],
      jetPrice: '$49,950,000',
      jetMainPic: gulf6508,
      summary: [
        'Exclusive Listing',
        'Low Flight hours',
        'One owner since new',
        'Private use only',
        'Forward Galley',
        'Four zone, 17 passenger configuration',
        'RRCC and MSP',
        '2020 mandates complied with',
        'WIFI',
        'Maintenance complied with at Gulfstream authorized facilities',
        'Four single VIP club seats',
        'Three place divan opposite two single VIP club seats',
        'Four place conference table',
        'Two 3 place divans (Two each TTOL seats)',
        'Additional valuable equipment / materials included in sale',
      ],
      serialNumber: 'https://www.globalair.com/ac-reg/search.aspx?serial=6354',
      regNum: 'https://www.globalair.com/ac-reg/search.aspx?regnum=B-603R',
      manufacturer: 'Gulfstream Aerospace',
      year: '2019',
      location: 'China',
      time: '582 hrs',
      address: `88 East Main St Mendham New Jersey (USA) 07945`,
      name: 'Philip Rushton',
      avionics: [
        '4 Honeywell DU-1310 EFIS',
        '3 Honeywell CDU',
        '3 Honeywell LASEREF VI IRS',
        '2 Honeywell GPS',
        '2 Honeywell DM-855 DME',
        '1 Gulfstream HGS-6250 HUD',
        '1 KollsmaEVS',
        '2 Honeywell DF-855 ADF',
        '2 Honeywell AH-1000 AHRS',
        '1 Honeywell NC-860A VHF COM',
        '2 Honeywell TR-865A VHF COM',
        '2 Collins HF-9034A w/SECAL HF COM',
        '1 Honeywell MCS-7120 SATCOM',
        '1 Honeywell TR-1 WRADAR',
        '2 Honeywell Mode S XPNDR',
        '1 Honeywell TCAS II w/change7.1 TCAS',
        '2 Honeywell EGP-100 GPWS',
        '1 Universal CVR-120R CVR',
        '1 Universal FDR-25 FDR',
        '1 Honeywell LP-860 LSS',
      ],
      status: '48 month completed in March 2023',
      features:
        'Owner prepared to close in 2023 and escrow agreed funds for an ARCS in early 2024.',
    },
  ],
};

export const trendingAircrafts = (state = initialState, action) => {
  switch (action.type) {
    case TRENDING_AIRCRAFT.LISTS_ALL_AIRCRAFTS:
      return {
        ...state,
      };

    case TRENDING_AIRCRAFT.LIST_ONE_AIRCRAFT:
      return {
        ...state,
        trendingAircrafts: state.trendingAircrafts.map((trendingAircraft) =>
          trendingAircraft.jetId === action.payload.id
            ? action.payload
            : trendingAircraft,
        ),
      };

    default:
      return state;
  }
};
