export const TRENDING_AIRCRAFT = {
  LISTS_ALL_AIRCRAFTS: 'LISTS_ALL_AIRCRAFTS',
  LIST_ONE_AIRCRAFT: 'LIST_ONE_AIRCRAFT',
};

export const LATEST_AIRCRAFT = {
  LISTS_ALL_AIRCRAFTS: 'LISTS_ALL_AIRCRAFTS',
  LIST_ONE_AIRCRAFT: 'LIST_ONE_AIRCRAFT',
};
